server:
  port: 8083

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: NOTIFICATION-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost